version: '3.11'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=budget-api-db
      - POSTGRES_USER=budget-api
      - POSTGRES_PASSWORD=badaras
      - PGDATA=/var/lib/postgresql/data/pgdata/
    ports:
      - "5432:5432"

volumes:
  postgres_data:
