# Generated by Django 5.0b1 on 2023-11-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExpenseCategory",
            options={"verbose_name_plural": "Expense categories"},
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(help_text="Display name of the category", max_length=128),
                ),
                (
                    "raw_name",
                    models.CharField(
                        help_text="Original name of the caterogy, obtained from csv statement. "
                        "Used to match a newExpense to a customized ExpenseCategory."
                    ),
                ),
            ],
        ),
    ]
