# Generated by Django 5.0rc1 on 2023-12-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credit_card", "0003_expense"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense",
            old_name="installments",
            new_name="installment",
        ),
        migrations.AddField(
            model_name="expense",
            name="total_installments",
            field=models.IntegerField(default=1),
        ),
    ]
